### ISSUE TITLE
两个模块载入有问题， 

### ISSUE THREAD

**Issue by Walkman1W** [AgoraIO/openai-realtime-python#5]
模块载入有问题：
main.py   
from agora_realtime_ai_api.rtc import RtcEngine, RtcOptions    
找不到 agora_realtime_ai_api 

agent.py 
from agora.rtc.rtc_connection import RTCConnection, RTCConnInfo
from attr import dataclass

from agora_realtime_ai_api.rtc import Channel, ChatMessage, RtcEngine, RtcOptions
找不到 agora   ， agora_realtime_ai_api  

运行：python -m realtime_agent.main server

报错：
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Code\OpenAI\openai-realtime-python\realtime_agent\main.py", line 13, in <module>
    from .agent import InferenceConfig, RealtimeKitAgent
  File "C:\Code\OpenAI\openai-realtime-python\realtime_agent\agent.py", line 8, in <module>
    from agora.rtc.rtc_connection import RTCConnection, RTCConnInfo
ModuleNotFoundError: No module named 'agora.rtc.rtc_connection'

![image](https://github.com/user-attachments/assets/fa3ba832-3970-4a1d-bc77-e37de0eca409)
![image](https://github.com/user-attachments/assets/4e928da8-fdf9-4c20-989a-ae4bc3ec5eac)
![image](https://github.com/user-attachments/assets/abfd4420-b710-42e9-ae6a-31251d858d80)
![image](https://github.com/user-attachments/assets/31263878-7e1e-4167-993b-647cc5f39a2a)

**Comment by plutoless** [comment]
have you tried install depdencies in requirements.txt?
